amcl:
  ros__parameters:
    use_sim_time: true
    global_frame_id: "map"
    odom_frame_id:   "odom"
    base_frame_id:   "base_footprint"
    scan_topic:      "scan"
    min_particles: 500
    max_particles: 2000
    tf_broadcast: true
