# 地図作成用のSLAM Toolboxのパラメータ設定ファイル
slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom              # 例: odom / simple_robot/odom 等、実環境に合わせる
    map_frame: map
    base_frame: base_link         # 例: base_link / simple_robot/base_link 等
    resolution: 0.05
    mode: "mapping"
    scan_topic: "/scan"           # Unity側が/lidarなら "/lidar" に
